import Image from "next/image";
import Link from "next/link";
import { env } from "node:process";
import { BrandFitCheck, BrandInquiry } from "@/components/BrandInquiry";
import { FAQAccordion } from "@/components/FAQAccordion";
import { TrackedLink } from "@/components/TrackedLink";
import { campaigns, won } from "@/data/campaigns";
import { faqItems } from "@/data/faqs";
import { absoluteUrl, createPageMetadata, team } from "@/data/site";

const title = "브랜드 공동구매 입점·상품 제안 | 거상커머스";
const description = "거상커머스에 공동구매 상품을 제안해 주세요. 상품 경쟁력, 가격, 재고, 배송 체계와 콘텐츠 적합성을 검토하고 인플루언서 매칭과 캠페인 운영을 지원합니다.";
export const metadata = createPageMetadata(title, description, "/brands");

const problems = ["좋은 상품이 있지만 적합한 판매 채널이 부족함", "상품과 맞는 인플루언서를 직접 찾기 어려움", "공동구매 판매가와 수익 구조 설계가 어려움", "콘텐츠 가이드와 일정 관리 경험이 부족함", "인플루언서·주문·배송 커뮤니케이션이 복잡함", "단발성 노출이 아닌 실제 판매 구조가 필요함"];
const services = [["상품 경쟁력 검토", "정상가, 온라인 판매가, 상품 차별성, 리뷰와 콘텐츠 적합성을 확인합니다."], ["공동구매 가격 구조 설계", "공급가, 공동구매 판매가, 배송비와 참여자 역할을 고려해 판매 구조를 협의합니다."], ["인플루언서 후보 발굴", "상품 카테고리와 예상 고객층에 적합한 콘텐츠 채널과 인플루언서를 검토합니다."], ["캠페인 제안과 매칭", "인플루언서에게 상품과 조건을 제안하고 진행 가능 여부를 확인합니다."], ["콘텐츠 방향 설계", "상품의 핵심 포인트, 콘텐츠 형식, 필수 정보와 광고 표시 기준을 정리합니다."], ["일정과 운영 관리", "제품 체험, 콘텐츠 제작, 판매 오픈과 마감 일정을 조율합니다."], ["판매·배송 커뮤니케이션", "판매 현황, 재고, 출고 일정과 운영 이슈를 브랜드와 인플루언서 사이에서 중계합니다."], ["판매 마감과 정산 안내", "주문·취소·반품 내역과 합의된 정산 기준을 바탕으로 관련 커뮤니케이션을 지원합니다."]];
const wanted = [["차별점이 명확한 상품", "기존 상품과 구분되는 특징과 고객이 선택할 이유가 있는 상품"], ["콘텐츠로 보여주기 좋은 상품", "사용 장면, 맛, 구성, 디자인이나 변화를 영상과 이미지로 전달하기 좋은 상품"], ["가격 경쟁력이 있는 상품", "기존 온라인 판매가와 비교해 고객 혜택이 명확한 공동구매 구성을 만들 수 있는 상품"], ["안정적인 공급이 가능한 상품", "판매 기간 동안 필요한 재고를 확보하고 품절과 배송 지연에 대응할 수 있는 상품"], ["배송 체계가 준비된 상품", "주문 확인, 포장, 송장 등록과 소비자 배송이 가능한 상품"], ["정보와 서류가 준비된 상품", "상품 상세정보, 이미지, 원재료·성분, 표시사항과 필요한 인증자료를 제공할 수 있는 상품"]];
const outputs = ["상품 및 고객 적합성 검토", "공동구매 상품 구성", "공동구매 제안 판매가", "역할별 수익·비용 구조", "추천 인플루언서 분야", "추천 콘텐츠 형식", "판매 일정", "배송 및 고객응대 역할", "정산 기준", "필수 표시와 금지 표현"];
const steps = [["공동구매 상품 제안", "상품과 기본 운영 조건을 접수합니다."], ["상품·가격·재고 검토", "가격 경쟁력과 공급 가능 수량을 확인합니다."], ["캠페인 구조와 역할 설계", "상품 구성, 업무 범위와 정산 기준을 협의합니다."], ["인플루언서 발굴 및 제안", "예상 고객층과 맞는 후보에게 캠페인을 제안합니다."], ["콘텐츠와 판매 일정 확정", "필수 정보, 콘텐츠 방향과 오픈 일정을 정합니다."], ["판매 운영과 상품 배송", "판매 현황과 출고 이슈를 역할에 따라 확인합니다."], ["판매 마감과 정산", "취소·반품을 반영하고 합의된 기준으로 정산합니다."]];
const roles = { "브랜드·공급사": ["정확한 상품 정보 제공", "공동구매 가격과 공급 조건 협의", "판매 가능한 재고 확보", "상품 이미지와 필수 자료 제공", "필요 시 제품 샘플 제공 협의", "주문 확인과 택배 발송", "상품 관련 고객문의 대응", "교환·반품 처리"], "거상커머스": ["상품과 판매 조건 검토", "캠페인 구성과 일정 제안", "인플루언서 후보 발굴", "인플루언서 제안과 커뮤니케이션", "콘텐츠 가이드와 필수 정보 안내", "판매 현황 확인 지원", "배송·운영 이슈 중계", "정산 커뮤니케이션 지원"] };
const difficult = ["재고 수량과 출고 일정이 불명확한 경우", "온라인 판매가보다 공동구매 가격 경쟁력이 없는 경우", "필요한 상품 정보와 표시사항을 제공할 수 없는 경우", "검증되지 않은 효능이나 과장된 표현을 요구하는 경우", "교환·반품과 소비자 응대 주체가 없는 경우", "국내 판매에 필요한 인증이나 절차가 확인되지 않은 경우", "인플루언서에게 판매량을 일방적으로 보장하도록 요구하는 경우", "기존 유통채널과 가격 충돌 위험이 큰 경우"];
const campaignSlugs = ["manuka-royal-jelly-mgo-300", "gooday-propolis-spray", "quokkies-macadamia"];
const currentCampaigns = campaigns.filter((item) => campaignSlugs.includes(item.slug));
const faqIds = ["brand-eligibility", "brand-approval", "brand-costs", "brand-pricing", "brand-creator-choice", "brand-fulfillment", "brand-samples", "brand-imported-products"];
const brandFaqs = faqIds.map((id) => faqItems.find((item) => item.id === id)).filter((item): item is NonNullable<typeof item> => Boolean(item));

export default function BrandsPage() {
  const formEnabled = Boolean((env.BRAND_FORM_ENDPOINT || env.NEXT_PUBLIC_BRAND_FORM_ENDPOINT || "").trim());
  const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "홈", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "브랜드 공동구매 상품 제안", item: absoluteUrl("/brands") }] }, { "@type": "FAQPage", mainEntity: brandFaqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }, { "@type": "ItemList", name: "현재 제안 가능한 공동구매 캠페인", itemListElement: currentCampaigns.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, url: absoluteUrl(`/campaigns/${item.slug}`) })) }] };
  return <main className="brands-sales-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="brand-sales-hero"><div className="shell brand-sales-hero-inner"><div><span className="eyebrow">FOR BRANDS</span><h1>좋은 상품이 영향력 있는 콘텐츠를 만나도록</h1><p>상품은 준비됐지만 판매 채널과 적합한 인플루언서를 찾기 어렵다면 거상커머스에 제안해 주세요. 상품 검토부터 캠페인 구조, 인플루언서 매칭과 운영 커뮤니케이션을 함께합니다.</p><strong>입점 신청만으로 공동구매 진행이나 판매가 확정되는 것은 아닙니다. 상품과 공급 조건을 검토한 후 진행 가능성을 안내합니다.</strong><div className="brand-sales-actions"><TrackedLink className="gradient-button" href="#inquiry" analyticsEvent="click_brand_inquiry">공동구매 상품 제안하기</TrackedLink><Link className="outline-button" href="#brand-fit-check">입점 가능성 확인하기</Link></div><div className="brand-sales-microcopy">{["식품·건강식품·뷰티·생활용품 등 검토", "국내외 브랜드 및 수입상품 제안 가능", "안정적인 재고와 배송 체계 필요", "상품과 조건 검토 후 캠페인 진행 여부 협의"].map((item) => <span key={item}>✓ {item}</span>)}</div></div><div className="brand-sales-panel"><span>GEOSANG COMMERCE</span><h2>좋은 상품에 맞는<br />인플루언서와 판매 구조를 연결합니다</h2><p>상품 경쟁력, 가격, 재고, 배송 체계와 콘텐츠 적합성을 검토해 공동구매 캠페인을 설계합니다.</p></div></div></section>
    <section className="shell section-gap"><div className="center-head"><span className="eyebrow">BRAND CHALLENGES</span><h2>이런 고민이 있다면 거상커머스와 상담해 보세요</h2></div><div className="brand-problem-grid">{problems.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item}</h3></article>)}</div></section>
    <section className="brand-service-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">WHAT WE DO</span><h2>상품 검토부터 운영 커뮤니케이션까지</h2><p>브랜드의 고민을 캠페인에 필요한 구체적인 업무로 나눠 함께 정리합니다.</p></div><div className="brand-service-grid">{services.map(([heading, copy], index) => <article key={heading}><span>{String(index + 1).padStart(2, "0")}</span><h3>{heading}</h3><p>{copy}</p></article>)}</div></div></section>
    <BrandFitCheck />
    <section className="shell section-gap"><div className="center-head"><span className="eyebrow">WHAT WE LOOK FOR</span><h2>이런 상품을 우선 검토합니다</h2></div><div className="brand-wanted-grid">{wanted.map(([heading, copy]) => <article key={heading}><h3>{heading}</h3><p>{copy}</p></article>)}</div></section>
    <section className="brand-category-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">CATEGORIES</span><h2>다양한 카테고리의 상품을 검토합니다</h2></div><div className="brand-category-tags">{["식품", "건강식품", "뷰티", "생활용품", "육아·가족", "반려동물", "여행·캠핑", "홈카페", "패션·잡화", "기타 제안"].map((item) => <span key={item}>{item}</span>)}</div><p className="brand-notice">카테고리만으로 입점을 보장하지 않습니다. 건강식품·화장품·식품은 국내 판매와 광고에 필요한 표시·인증 조건을 확인할 수 있어야 합니다.</p></div></section>
    <section className="shell brand-current-campaigns section-gap"><div className="section-head"><div><span className="eyebrow">CURRENT CAMPAIGNS</span><h2>현재 이런 상품을 공동구매로 제안하고 있습니다</h2></div><Link href="/campaigns">전체 캠페인 보기 →</Link></div><div className="brand-campaign-grid">{currentCampaigns.map((item) => { const lead = item.variants[0]; return <article key={item.slug}><div className={`brand-campaign-image ${item.imageTreatment || "product"}`}><Image src={item.image!} alt={item.imageAlt || item.name} fill sizes="(max-width: 900px) 100vw, 33vw" /></div><div className="brand-campaign-body"><div><span>{item.category}</span><b>{item.brand}</b></div><h3>{item.name}</h3><p>대표 구성 · {lead.composition}</p><strong>{won(lead.offerPrice)}</strong><div className="brand-campaign-meta"><span>{item.shipping}</span><span>{item.status === "제안 가능" ? "공동구매 제안 가능" : item.status}</span></div><Link href={`/campaigns/${item.slug}`}>상품 자세히 보기 →</Link></div></article>; })}</div><p className="brand-notice">위 상품은 거상커머스의 현재 캠페인 구성 예시입니다. 상품별 공급 조건과 진행 상태는 변경될 수 있습니다.</p></section>
    <section className="brand-output-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">CAMPAIGN OUTPUT</span><h2>상담 후 이런 내용을 함께 정리합니다</h2></div><div className="brand-output-grid">{outputs.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="shell brand-process-section section-gap"><div className="center-head"><span className="eyebrow">HOW IT WORKS</span><h2>브랜드 공동구매 진행 절차</h2></div><ol>{steps.map(([heading, copy], index) => <li key={heading}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{heading}</h3><p>{copy}</p></div></li>)}</ol><div className="center-action"><Link className="outline-button" href="/process#brand-process">브랜드 공동구매 전체 과정 보기</Link></div></section>
    <section className="brand-role-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">ROLE &amp; RESPONSIBILITY</span><h2>브랜드와 거상커머스는 이렇게 협업합니다</h2></div><div className="brand-role-grid">{Object.entries(roles).map(([heading, items]) => <article key={heading}><h3>{heading}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div><p className="brand-notice">세부 역할과 책임 범위는 상품과 캠페인 계약 조건에 따라 달라질 수 있으며 진행 전에 확정합니다.</p></div></section>
    <section className="shell brand-cost section-gap"><div><span className="eyebrow">COST &amp; AGREEMENT</span><h2>비용과 조건은 업무 범위를 확인한 후 제안합니다</h2><p>공동구매의 비용 구조는 상품 공급 조건, 배송 방식, 인플루언서 섭외 범위, 콘텐츠 제작, 광고 집행과 운영 업무에 따라 달라질 수 있습니다.</p></div><div>{["공동구매 판매 수수료", "인플루언서 수익 배분", "상품 샘플 및 배송 비용", "별도 콘텐츠 제작비", "광고 집행비", "추가 운영 대행비"].map((item) => <span key={item}>{item}</span>)}<p>해당 항목이 모든 캠페인에 일괄 적용되는 것은 아닙니다. 필요한 업무와 조건을 확인한 뒤 견적 또는 개별 계약으로 안내합니다.</p></div></section>
    <section className="brand-difficult-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">ENTRY GUIDE</span><h2>다음 조건은 진행이 어려울 수 있습니다</h2></div><div className="brand-difficult-grid">{difficult.map((item) => <span key={item}>× {item}</span>)}</div><p>일부 조건이 부족하더라도 상담을 통해 보완 가능 여부를 확인할 수 있습니다.</p></div></section>
    <section className="shell brand-team-section section-gap"><div className="center-head"><span className="eyebrow">COMMERCE TEAM</span><h2>마케팅과 콘텐츠를 이해하는 운영팀이 검토합니다</h2><p>거상커머스는 거상스쿨과 거상마케팅센터의 콘텐츠·마케팅 경험을 바탕으로 상품과 인플루언서의 적합성을 검토합니다.</p></div><div className="brand-team-grid">{team.map((member) => <article key={member.name}><Image src={member.image} alt={`${member.name} ${member.role}`} width={360} height={420}/><div><span>{member.role}</span><h3>{member.name}</h3><ul>{member.lines.map((line) => <li key={line}>{line}</li>)}</ul><a href={member.instagram} target="_blank" rel="noopener noreferrer">Instagram · {member.handle} ↗</a></div></article>)}</div></section>
    <BrandInquiry formEnabled={formEnabled} />
    <section className="soft-section section-gap"><div className="shell faq-wrap"><div><span className="eyebrow">BRAND FAQ</span><h2>상품을 제안하기 전 확인해 주세요</h2><p>입점 검토, 가격, 인플루언서 선정과 배송에 관한 기본 안내입니다.</p><Link className="faq-all-link" href="/faq">브랜드 입점 FAQ 전체 보기 →</Link></div><FAQAccordion items={brandFaqs}/></div></section>
    <section className="brand-seo-copy shell"><p>거상커머스는 브랜드 공동구매 입점과 상품 제안을 검토하는 인플루언서 공동구매 플랫폼입니다. 실제 공급 가능한 상품과 체계적인 공동구매 운영 지원을 바탕으로 상품, 가격, 재고, 배송과 콘텐츠 적합성을 확인합니다.</p></section>
  </main>;
}
