import Image from "next/image";
import { FAQAccordion } from "@/components/FAQAccordion";
import { ProcessTimeline } from "@/components/ProcessTimeline";
import { TrackedLink } from "@/components/TrackedLink";
import { Campaign, discountRate, won } from "@/data/campaigns";

export function QuokkiesCampaignDetail({ item }: { item: Campaign }) {
  const detail = item.quokkiesDetail;
  if (!detail) return null;
  const lead = item.variants[0];
  const applyHref = `/creators?campaign=${item.slug}#apply`;
  return <main className="quokkies-page">
    <section className="quokkies-hero"><div className="shell quokkies-hero-grid"><div className="quokkies-hero-image"><Image src={detail.heroImage} alt={item.imageAlt || item.name} width={1200} height={1054} priority sizes="(max-width: 900px) 100vw, 52vw" /></div><div className="quokkies-hero-copy"><span className="quokkies-kicker">QUOKKIES · 호주산 식품 · 120g</span><p className="quokkies-english">{detail.englishName}</p><h1>{detail.displayName}</h1><p className="quokkies-intro">{detail.introduction}</p><div className="quokkies-flavor-pills"><span>바닐라 로스티드</span><span>드라이 로스티드</span></div><div className="quokkies-price"><span>{discountRate(lead.regularPrice, lead.offerPrice)}%</span><strong>{won(lead.offerPrice)}</strong><del>{won(lead.regularPrice)}</del></div><p className="quokkies-lead-composition">대표 구성 · {lead.composition}</p><p className="quokkies-note">공동구매 제안 기준가이며 맛 구성, 오프너 제공 방식, 판매 일정과 세부 조건은 협의 후 확정됩니다.</p><TrackedLink href={applyHref} analyticsEvent="click_creator_apply" analyticsData={{ campaign_slug: item.slug }} className="quokkies-primary-button">이 상품 제안받기</TrackedLink></div></div><div className="shell quokkies-facts">{detail.productFacts.map((x) => <div key={x.label}><small>{x.label}</small><strong>{x.value}</strong></div>)}</div></section>

    <section className="shell quokkies-section"><div className="quokkies-section-head"><span>WHY QUOKKIES</span><h2>재미있게 열고, 두 가지 맛으로 즐겨요</h2></div><div className="quokkies-highlight-grid">{detail.highlights.map((x, i) => <article key={x.title}><span>{String(i + 1).padStart(2, "0")}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></section>

    <section className="quokkies-cream quokkies-section"><div className="shell"><div className="quokkies-section-head"><span>TWO FLAVORS</span><h2>초록과 주황, 취향에 맞는 두 가지 맛</h2></div><div className="quokkies-flavors">{detail.flavors.map((x, i) => <article className={i === 0 ? "vanilla" : "dry"} key={x.name}><span>{x.color} 패키지</span><h3>{x.name}</h3><p>{x.description}</p><div>{x.ideas.map((idea) => <b key={idea}>{idea}</b>)}</div></article>)}</div></div></section>

    <section className="shell quokkies-section quokkies-origin-grid"><Image src={detail.images.origin} alt="호주의 대표적인 마카다미아 생산 지역을 보여주는 지도" width={900} height={760} sizes="(max-width: 900px) 100vw, 48vw" /><div><span className="quokkies-kicker">FROM AUSTRALIA</span><h2>마카다미아의 고장, 호주에서 왔습니다</h2><p>쿼키즈는 호주에서 생산된 마카다미아를 사용합니다. 호주의 자연환경과 큼직한 마카다미아 알맹이는 원산지와 식감을 강조하는 콘텐츠 소재로 활용하기 좋습니다.</p><p>호주의 대표적인 마카다미아 생산지로는 퀸즐랜드와 뉴사우스웨일스 지역 등이 알려져 있습니다.</p><strong>엄선한 호주산 프리미엄 마카다미아</strong></div></section>

    <section className="quokkies-green quokkies-section"><div className="shell quokkies-size-grid"><div><span className="quokkies-kicker">BIG NUT EXPERIENCE</span><h2>눈으로 확인되는 큼직한 마카다미아</h2><p>큼직하고 균일한 마카다미아를 선별한 제품입니다. 수치나 등급을 단정하기보다 실제 제품의 크기와 인쉘 타입을 화면에서 자연스럽게 보여주는 콘텐츠에 잘 어울립니다.</p><div className="quokkies-size-cards"><article><span>LOOK</span><strong>큼직한 알맹이</strong><p>제품을 직접 보여주는 크기 비교 콘텐츠</p></article><article><span>TEXTURE</span><strong>통째로 즐기는 인쉘 타입</strong><p>껍질을 여는 과정과 알맹이 식감을 함께 소개</p></article></div></div><div className="quokkies-nut-art" aria-hidden><span>Q</span><b>MACADAMIA</b></div></div></section>

    <section className="shell quokkies-section quokkies-package-grid"><Image src={detail.images.package} alt="쿼키즈 마카다미아 초록색과 주황색 지퍼형 스탠딩 파우치" width={900} height={820} sizes="(max-width: 900px) 100vw, 48vw" /><div><span className="quokkies-kicker">ZIPPER POUCH</span><h2>신선한 보관을 고려한 지퍼형 파우치</h2><p>수분과 외부 환경으로부터 제품을 보호하고, 개봉 후에도 보관하기 편리한 스탠딩 파우치 형태입니다.</p><ul>{detail.packagePoints.map((x) => <li key={x}>{x}</li>)}</ul></div></section>

    <section className="quokkies-orange quokkies-section"><div className="shell quokkies-opener-grid"><div><span className="quokkies-kicker">HOW TO OPEN</span><h2>껍질을 여는 순간까지 재미있게</h2><p>전용 오프너를 사용해 직접 껍질을 여는 과정도 쿼키즈 마카다미아의 콘텐츠 포인트입니다.</p><ol>{detail.openerSteps.map((x, i) => <li key={x}><span>{i + 1}</span>{x}</li>)}</ol><b>껍질을 열 때 무리한 힘을 가하지 말고 손이 다치지 않도록 주의해 주세요.</b><p className="quokkies-opener-note">오프너 제공 수량과 방식은 공동구매 구성에 따라 달라질 수 있습니다.</p></div><Image src={detail.images.opener} alt="전용 오프너를 마카다미아 껍질 홈에 끼워 여는 모습" width={900} height={760} sizes="(max-width: 900px) 100vw, 44vw" /></div></section>

    <section className="shell quokkies-section"><div className="quokkies-section-head"><span>DIFFERENCE</span><h2>쿼키즈는 무엇이 다른가요?</h2><p>우열을 단정하지 않고 포장, 형태와 콘텐츠 경험의 차이를 비교했습니다.</p></div><div className="quokkies-table-wrap"><table><thead><tr><th>비교 항목</th><th>일반 제품</th><th>쿼키즈 마카다미아</th></tr></thead><tbody>{detail.comparison.map((x) => <tr key={x.label}><th>{x.label}</th><td>{x.general}</td><td>{x.quokkies}</td></tr>)}</tbody></table></div></section>

    <section className="quokkies-cream quokkies-section"><div className="shell"><div className="quokkies-section-head"><span>RECOMMEND</span><h2>이런 분들에게 추천하기 좋습니다</h2></div><div className="quokkies-recommend-grid">{detail.recommendations.map((x, i) => <article key={x}><span>{String(i + 1).padStart(2, "0")}</span><p>{x}</p></article>)}</div><div className="quokkies-caution"><h3>섭취 전 확인해 주세요</h3><ul>{detail.cautions.map((x) => <li key={x}>{x}</li>)}</ul></div></div></section>

    <section className="shell quokkies-section"><div className="quokkies-section-head"><span>CONTENT PLAYBOOK</span><h2>이런 콘텐츠로 소개하기 좋습니다</h2></div><div className="quokkies-content-grid"><div><h3>콘텐츠 아이디어</h3><ol>{detail.contentIdeas.map((x) => <li key={x}>{x}</li>)}</ol></div><div><h3>추천 크리에이터</h3><div className="quokkies-tags">{detail.creatorTypes.map((x) => <span key={x}>{x}</span>)}</div><h3>숏폼 훅 예시</h3><ul>{detail.hooks.map((x) => <li key={x}>“{x}”</li>)}</ul></div></div></section>

    <section className="quokkies-cream quokkies-section"><div className="shell"><div className="quokkies-section-head"><span>PRICE OPTIONS</span><h2>공동구매 상품 구성</h2></div><div className="quokkies-price-cards">{item.variants.map((x) => <article key={x.composition}><h3>{x.composition}</h3><p><small>정상가</small><del>{won(x.regularPrice)}</del></p>{x.onlineLowestPrice ? <p><small>온라인 최저가</small><span>{won(x.onlineLowestPrice)}</span></p> : null}<p className="offer"><small>공동구매 제안가</small><strong>{won(x.offerPrice)}</strong><b>{discountRate(x.regularPrice, x.offerPrice)}% 할인</b></p><em>{item.shipping}</em></article>)}</div><p className="quokkies-note">가격은 공동구매 제안 기준이며 맛 조합, 오프너 제공 수량, 판매 일정과 세부 조건은 협의 후 최종 확정됩니다.</p></div></section>

    <section className="shell quokkies-section"><div className="quokkies-section-head"><span>CAMPAIGN SUPPORT</span><h2>거상커머스가 함께합니다</h2></div><div className="quokkies-support-grid">{detail.supportItems.map((x, i) => <article key={x}><span>{String(i + 1).padStart(2, "0")}</span><strong>{x}</strong></article>)}</div><p className="quokkies-support-note">{detail.supportNote}</p></section>
    <section className="quokkies-green quokkies-section"><div className="shell"><div className="quokkies-section-head light"><span>PROCESS</span><h2>공동구매 진행 과정</h2></div><ProcessTimeline /></div></section>
    <section className="quokkies-cream quokkies-section"><div className="shell quokkies-faq-grid"><div><span className="quokkies-kicker">FAQ</span><h2>자주 묻는 질문</h2><p>맛 구성과 오프너, 진행 조건을 신청 전에 확인해 보세요.</p></div><FAQAccordion items={detail.faqs} /></div></section>
    <section className="shell quokkies-final-cta"><div><span>CREATOR PARTNERSHIP</span><h2>{detail.finalCta.title}</h2><p>{detail.finalCta.description}</p></div><TrackedLink href={applyHref} analyticsEvent="click_creator_apply" analyticsData={{ campaign_slug: item.slug }} className="quokkies-primary-button">{detail.finalCta.button}</TrackedLink></section>
    <div className="sticky-detail-cta"><span><strong>{detail.displayName}</strong><small>{item.shipping} · 제안가 {won(lead.offerPrice)}부터</small></span><TrackedLink href={applyHref} analyticsEvent="click_creator_apply" analyticsData={{ campaign_slug: item.slug }} className="gradient-button">{detail.finalCta.button}</TrackedLink></div>
  </main>;
}
