import type { Metadata } from "next";
import { CampaignCard } from "@/components/CampaignCard";
import { FAQAccordion } from "@/components/FAQAccordion";
import { InquiryForm } from "@/components/InquiryForm";
import { PageHero } from "@/components/PageHero";
import { ProcessTimeline } from "@/components/ProcessTimeline";
import { campaigns } from "@/data/campaigns";
import { commonFaqs } from "@/data/site";
export const metadata: Metadata = { title:{absolute:"인플루언서 공동구매 모집 | 거상커머스"}, description:"인스타그램, 틱톡, 유튜브, 쇼츠에서 활동하는 인플루언서를 위한 공동구매 캠페인을 확인하고 제안받아 보세요.", alternates:{canonical:"/creators"} };
export default function CreatorsPage(){ return <main><PageHero eyebrow="CREATORS" title="좋은 콘텐츠가 좋은 제품을 만나는 순간" description="팔로워 규모보다 상품과 콘텐츠의 적합성을 중요하게 봅니다. 콘텐츠에 집중할 수 있도록 운영을 함께합니다."/><section className="shell section-gap"><div className="center-head"><span className="eyebrow">WHO CAN APPLY</span><h2>이런 크리에이터를 기다립니다</h2></div><div className="feature-grid three">{["인스타그램·틱톡·유튜브·쇼츠 활동자","제품을 직접 이해하고 진정성 있게 소개하는 분","캠페인 일정과 표기 가이드를 성실히 지키는 분"].map((x,i)=><article key={x}><span>0{i+1}</span><strong>{x}</strong></article>)}</div></section><section className="soft-section section-gap"><div className="shell"><div className="center-head"><span className="eyebrow">SUPPORT</span><h2>제공되는 운영 지원</h2></div><div className="feature-grid">{["검토된 상품 제안","재고 부담 없는 진행","공급·배송 운영 지원","콘텐츠 자료 안내","판매 현황 확인 지원","정산 일정 안내"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></article>)}</div></div></section><section className="shell section-gap"><div className="center-head"><span className="eyebrow">PROCESS</span><h2>지원부터 정산까지</h2></div><ProcessTimeline/></section><section className="shell section-gap"><div className="section-head"><div><span className="eyebrow">OPEN NOW</span><h2>현재 모집 캠페인</h2></div></div><div className="campaign-grid home-grid">{campaigns.filter(x=>x.status==="모집 중" || x.status==="제안 가능").map(x=><CampaignCard key={x.slug} campaign={x}/>)}</div></section><section className="soft-section section-gap"><div className="shell faq-wrap"><div><span className="eyebrow">FAQ</span><h2>지원 전 확인해 주세요</h2></div><FAQAccordion items={commonFaqs.slice(0,3)}/></div></section><section id="apply" className="shell form-section section-gap"><div className="form-intro"><span className="eyebrow">APPLY NOW</span><h2>인플루언서 지원</h2><p>필수 정보를 남겨 주시면 상품과 채널의 적합성을 검토합니다. 폼 연동 전에는 실제 접수되지 않는 개발용 확인 메시지가 표시됩니다.</p></div><InquiryForm kind="creator"/></section></main> }
